=== GVogeler/Potthast/data/potthast.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
  <xs:element name="potthast">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="o"/>
        <xs:element ref="u"/>
      </xs:choice>
      <xs:attribute name="papst" use="required"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:annotation>
      <xs:documentation>a single entry in the Regesta ("Urkunde")</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nr"/>
        <xs:element minOccurs="0" ref="fehlt"/>
        <xs:element minOccurs="0" ref="Referenz"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="e"/>
        <xs:element minOccurs="0" ref="an"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="o">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="nr"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="e"/>
      </xs:sequence>
      <xs:attribute name="n"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="nr" type="xs:string"/>
  <xs:element name="fehlt">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Referenz" type="xs:NMTOKEN"/>
  <xs:element name="an">
    <xs:annotation>
      <xs:documentation>recipients listed as "auch an" (also to) in the Regesta</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="e"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="e">
    <xs:annotation>
      <xs:documentation>A single receipient mentioned in the entry, usually the Latin dative form of a person or an institution.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="name"/>
        <xs:element minOccurs="0" ref="funktion"/>
        <xs:element minOccurs="0" ref="institution"/>
        <xs:element minOccurs="0" ref="ordo"/>
        <xs:element minOccurs="0" ref="ort"/>
        <xs:element minOccurs="0" ref="ortsbestimmung"/>
        <xs:element minOccurs="0" ref="inst2"/>
        <xs:element minOccurs="0" ref="repetit"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" ref="P"/>
          <xs:element minOccurs="0" ref="Bemerkungen"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="repetit">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:attribute name="reg"/>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="funktion">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:attribute name="reg"/>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="institution">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ordo">
    <xs:annotation>
      <xs:documentation>The assignemnt to a religious order, currently not used (mixed with "institution")</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ort">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:attribute name="reg"/>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ortsbestimmung">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="inst2">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Bemerkungen">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="P">
    <xs:annotation>
      <xs:documentation>The patronage of a Saint mentioned as part of the identification.</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="kommentar"/>
        <xs:element ref="orig"/>
      </xs:choice>
      <xs:assert test="normalize-space(string(.)) != ''"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="orig" type="xs:string"/>
  <xs:element name="kommentar">
    <xs:complexType mixed="true">
      <xs:attribute name="reg"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GVogeler/Potthast/data/HONO3-3.xml
<?xml version="1.0" encoding="UTF-8"?><potthast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="potthast.xsd" xml:id="Honorius3-3" papst="Honorius III.">
<u><nr>7013</nr><Referenz>7013</Referenz>
<e><institution>moniales</institution><ort>Goslaria</ort><P>S.Maria</P></e></u>
<u><nr>7014</nr><Referenz>7014</Referenz>
<e><name>(Andreas)</name><funktion>ep.</funktion><ort>Pragensis</ort></e></u>
<u><nr>7015</nr><Referenz>7015</Referenz>
<e><ordo>OCist</ordo><ort>Cistercium</ort></e>
<e><funktion>universi alii abbates</funktion><ordo>OCist</ordo></e></u>
<u><nr>7016</nr><Referenz>7016</Referenz>
<e><funktion>ep.</funktion><ort>Terdonensis</ort></e></u>
<u><nr>7017</nr><Referenz>7017</Referenz>
<e><name>V.</name><funktion>vir nobilis</funktion><ort>Cotinacensis</ort></e>
<e><name>ii, qui cum illo transibunt in Graeciam in Wilhelmi marchionis Montisferrati auxilium ad defensionem regni Thessalonicensis</name></e></u>
<u><nr>7018</nr><Referenz>7018</Referenz>
<e><funktion>universi abbates</funktion><ordo>OCist</ordo></e>
<e><funktion>fratres</funktion><institution>hospitale</institution><ort>Hierusalem</ort><P>S.Iohannes</P></e></u>
<u><nr>7019</nr><Referenz>7019</Referenz>
<e><funktion>capitulum</funktion><ort>Narbona</ort></e></u>
<u><nr>7020</nr><Referenz>7020</Referenz>
<e><funktion>decanus; capitulum</funktion><ort>Leodiensis</ort><P>S.Martinus</P></e></u>
<u><nr>7021</nr><Referenz>7021</Referenz>
<e><name>(Grumerius)</name><funktion>ep.</funktion><ort>Placentinus</ort></e>
<e><funktion>abbas</funktion><ort>Placentinus</ort><P>S.Savinus</P></e>
<e><funktion>praep.</funktion><ort>Placentinus</ort><P>S.Euphemia</P></e></u>
<u><nr>7022</nr><Referenz>7022</Referenz>
<e><name>(Albertus)</name><funktion>archiep.; leg. in partibus Italiae</funktion><ort>Magdeburgensis</ort></e></u>
<u><nr>7022a</nr><Referenz>7022a</Referenz>
<e><name>(Christianus)</name><funktion>ep.</funktion><ort>Prussia</ort><Bemerkungen>nur IX gez√§hlt</Bemerkungen></e></u>
<u><nr>7023</nr><Referenz>7023</Referenz>
<e><funktion>eccl.</funktion><ort>Spirensis</ort></e></u>
<u><nr>7024</nr><Referenz>7024</Referenz>
<e><name>(Guilelmus)</name><funktion>archiep.; apost.leg.</funktion><ort>Remi</ort></e></u>
<u><nr>7025</nr><Referenz>7025</Referenz>
<e><funktion>abbates; fratres</funktion><ordo>OPraem</ordo></e></u>
<u><nr>7026</nr><Referenz>7026</Referenz>
<e><funktion>abbates; universi fratres</funktion><ordo>OPraem</ordo></e></u>
<u><nr>7027</nr><Referenz>7027</Referenz>
<e><name>Reginaldus</name><funktion>rex </funktion><ort>Insulae</ort><Bemerkungen>zu Britannien</Bemerkungen></e></u>
<u><nr>7028</nr><Referenz>7028</Referenz>
<e><funktion>abbas</funktion><ort>de Cardon</ort></e>
<e><funktion>abbas</funktion><ort>de Bello Podio</ort></e>
<e><funktion>prior</funktion><ort>de Galer</ort><ortsbestimmung>Urgelensis dioc.</ortsbestimmung></e></u>
<u><nr>7029</nr><Referenz>7029</Referenz>
<e><funktion>decanus</funktion><ort>Salisburgensis</ort></e>
<e><name>magister H(ainricus)</name><funktion> canonicus</funktion><ort>Osterhoven</ort></e></u>
<u><nr>7030</nr><Referenz>7030</Referenz>
<e><funktion>abbas</funktion><ort>Raitenhaslach</ort></e>
<e><name>magister H(ainricus)</name><funktion> canonicus</funktion><ort>Osterhoven</ort></e></u>
<u><nr>7031</nr><Referenz>7031</Referenz>
<e>
            <name>Stephanus</name>
            <funktion>card. S.R.E.</funktion>
            <funktion>archiep.
                <ort>Cantuaria</ort></funktion>
        </e>

<e><funktion>archiep.</funktion><ort>Eboracensis</ort></e>
<e><funktion>suffraganei; praelati</funktion><ort>Cantuaria; Eboracensis</ort></e></u>
<u><nr>7032</nr><Referenz>7032</Referenz>
<e><name>Benno</name><funktion>ep.</funktion><ort>Senogalliensis</ort></e></u>
<u><nr>7033</nr><Referenz>7033</Referenz>
<e><funktion>abbatissa; conventus</funktion><ordo>OCist</ordo><ort>de Brailla</ort></e></u>
<u><nr>7034</nr><Referenz>7034</Referenz>
<e><funktion>cantor</funktion><ort>Paris</ort></e>
<e><name>magister Gaufridus</name><funktion> canonicus</funktion><ort>Paris</ort></e>
<e><name>magister Girardus</name><funktion> canonicus</funktion><ort>Paris</ort></e></u>
<u><nr>7035</nr><Referenz>7035</Referenz>
<e><name>Philippus</name><funktion>rex </funktion><ort>Franci</ort></e></u>
<u><nr>7036</nr><Referenz>7036</Referenz>
<e><name>(Stephanus)</name><funktion>abbas</funktion><institution>monasterium</institution><ort>Casinensis</ort></e>
<e><funktion>conventus</funktion><institution>monasterium</institution><ort>Casinensis</ort></e></u>
<u><nr>7037</nr><Referenz>7037</Referenz>
<e><funktion>conventus</funktion><institution>eccl.</institution><ordo>OSB</ordo><ort>S.Trudo</ort><ortsbestimmung>Leodiensis dioc.</ortsbestimmung></e></u>
<u><nr>7038</nr><Referenz>7038</Referenz>
<e><name>Constantinus</name><funktion>ep.</funktion><ort>Scalensis</ort></e>
<e><name>Matthaeus</name><funktion>archidiac.; canonicus</funktion><ort>Amalphitanus</ort></e>
<e><name>Constantinus Fabarus</name><funktion>diac. suus; canonicus</funktion><ort>Amalphitanus</ort></e></u>
<u><nr>7039</nr><Referenz>7039</Referenz>
<e><institution>abbatia</institution><ort>Spinosus locus <orig>Epinlieu</orig></ort><P>S.Maria</P></e></u>
<u><nr>7040</nr><Referenz>7040</Referenz>
<e><name>C(onradus)</name><funktion>ep.; apost.leg.</funktion><ort>Portuensis</ort></e></u>
<u><nr>7041</nr><Referenz>7041</Referenz>
<e><funktion>universi Christifideles, qui eccl. S.Mauritii ord.S.Aug. prope Halas Sax. in die dedicationis annuatim visitaverint</funktion></e></u>
<u><nr>7042</nr><Referenz>7042</Referenz>
<e><name>Andreas</name><funktion>ep.</funktion><ort>Pragensis</ort></e>
<e><name>Otokarus</name><funktion>rex </funktion><ort>Boemi</ort></e></u>
<u><nr>7043</nr><Referenz>7043</Referenz>
<e>
            <name>Fredericus</name>
            <funktion>rex 
            <ort>Sicilia</ort></funktion>
            <funktion>imperator 
            <ort>Romanorum</ort></funktion>
        </e>
</u>
<u><nr>7044</nr><Referenz>7044</Referenz>
<e><funktion>capitulum</funktion><ort>Bononia</ort></e></u>
<u><nr>7045</nr><Referenz>7045</Referenz>
<e><name>Angelica</name><funktion>fundatrix</funktion><institution>eccl.</institution><ort>de Guardia</ort><P>S.Maria de Monte</P></e></u>
<u><nr>7046</nr><Referenz>7046</Referenz>
<e><funktion>rector; fratres</funktion><institution>hospitale</institution><ort>S.Spiritus</ort><ortsbestimmung>Saxonia</ortsbestimmung></e></u>
<u><nr>7047</nr><Referenz>7047</Referenz>
<e><name>(Otto)</name><funktion>ep.</funktion><ort>Traiectensis</ort></e>
<e><name>W(illelmum)</name><funktion>quondam comes</funktion><ort>Hollandia</ort></e></u>
<u><nr>7048</nr><Referenz>7048</Referenz>
<e><funktion>decanus; capitulum</funktion><ort>Aniciensis</ort></e></u>
<u><nr>7049</nr><Referenz>7049</Referenz>
<e><funktion>ep.</funktion><ort>Ilerdensis</ort></e></u>
<u><nr>7050</nr><Referenz>7050</Referenz>
<e><name>Primogenitus</name><funktion>subdiac. suus; canonicus</funktion><ort>Zagrabiensis</ort></e></u>
<u><nr>7051</nr><Referenz>7051</Referenz>
<e><funktion>abbas</funktion><ort>S.Aegidius</ort><ortsbestimmung>Vesprimiensis dioc.</ortsbestimmung></e>
<e><funktion>abbas</funktion><ort>S.Iacobus</ort><Bemerkungen>Vesprimiensis dioc. oder Quinqueecclesiensis dioc.</Bemerkungen></e>
<e><funktion>abbas</funktion><ort>de Posega</ort><ortsbestimmung>Quinqueecclesiensis dioc.</ortsbestimmung><P>S.Petrus</P></e></u>
<u><nr>7052</nr><Referenz>7052</Referenz>
<e><funktion>abbas; conventus</funktion><institution>monasterium</institution><ort>Massilia</ort><P>S.Victor</P></e></u>
<u><nr>7053</nr><Referenz>7053</Referenz>
<e><funktion>consules</funktion><ort>Terracensis</ort></e></u>
<u><nr>7054</nr><Referenz>7054</Referenz>
<e><funktion>ep.; praep.</funktion><ort>Foroiuliensis</ort></e></u>
<u><nr>7055</nr><Referenz>7055</Referenz>
<e><funktion>archiepp.; epp.; alii praelati</funktion></e></u>
<u><nr>7056</nr><Referenz>7056</Referenz>
<e><funktion>prior; eccl.</funktion><ort>Pisanus</ort></e></u>
<u><nr>7057</nr><Referenz>7057</Referenz>
<e><funktion>prior</funktion><ort>Fossa Nova</ort></e></u>
<u><nr>7058</nr><Referenz>7058</Referenz>
<e><name>Eustorgius</name><funktion>archiep.</funktion><ort>Nicosiensis</ort></e></u>
<u><nr>7059</nr><Referenz>7059</Referenz>
<e><name>Petrus Leonis de Corneto</name></e></u>
<u><nr>7060</nr><Referenz>7060</Referenz>
<e><funktion>potestas; commune</funktion><ort>Massilia</ort></e></u>
<u><nr>7061</nr><Referenz>7061</Referenz>
<e><name>magister Guido</name><funktion> archidiac.</funktion><ort>Lemovicensis</ort></e>
<e><name>magister Durandus</name><funktion> archidiac.</funktion><ort>Lemovicensis</ort></e>
<e><name>Ar. Esperus</name><funktion>canonicus</funktion><ort>Lemovicensis</ort></e></u>
<u><nr>7062</nr><Referenz>7062</Referenz>
<e><funktion>decanus; cantor</funktion><ort>S.Audomarus</ort><ortsbestimmung>Morinensis dioc.</ortsbestimmung></e>
<e><name>P.</name><funktion>canonicus</funktion><ort>S.Audomarus</ort><ortsbestimmung>Morinensis dioc.</ortsbestimmung></e></u>
<u><nr>7063</nr><Referenz>7063</Referenz>
<e><funktion>capitulum</funktion><ort>Novariensis</ort></e></u>
<u><nr>7064</nr><Referenz>7064</Referenz>
<e><name>magister A(contius)</name><funktion> capellanus suus; apost.leg.</funktion></e></u>
<u><nr>7065</nr><Referenz>7065</Referenz>
<e><name>(Gunzellus)</name><funktion>archiep.</funktion><ort>Spalatensis</ort></e></u>
<u><nr>7066</nr><Referenz>7066</Referenz>
<e><funktion>abbas</funktion><ordo>OCist</ordo><ort>Vallis S.Petri</ort><ortsbestimmung>Coloniensis dioc.</ortsbestimmung></e>
<e><funktion>decanus; praep.</funktion><ort>Colonia</ort></e></u>
<u><nr>7067</nr><Referenz>7067</Referenz>
<e><name>(Guilelmus)</name><funktion>archiep.</funktion><ort>Remi</ort></e></u>
<u><nr>7068</nr><Referenz>7068</Referenz>
<e>
            <name>Fredericus</name>
            <funktion>rex 
            <ort>Sicilia</ort></funktion>
            <funktion>imperator
